import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),src=fs.readFileSync(path.join(root,'src/js/25-v35-reliability-safety.js'),'utf8');
const context={console,window:{}};vm.createContext(context);vm.runInContext(src,context);const core=context.window.OSCP_RELIABILITY_CORE;
const assert=(v,m)=>{if(!v)throw new Error(m)};
assert(core&&typeof core.storageUsage==='function','reliability core missing');
let u=core.storageUsage([['oscp_v16_a','x'.repeat(4000)],['other','y'.repeat(9999)]],'oscp_v16_',10000);assert(u.warning===true&&u.keys===1,'storage warning/prefix filtering failed');
const proof='0123456789abcdef0123456789abcdef',sha='a'.repeat(64),realistic={targets:[{id:'a',notes:`proof.txt = ${proof}\nMD5 ${proof}\nSHA256 ${sha}`,evidence:{proofValue:proof},report:{screens:`proof ${proof}`}}],evidenceVault:[{name:'proof.png',sha256:sha,note:'screenshot checksum'}]};
let findings=core.scanSecretLikeText(realistic);assert(findings.length===0,'proof/checksum false positive: '+JSON.stringify(findings));
findings=core.scanSecretLikeText({notes:'password=ExampleSecret123\nntlm=0123456789abcdef0123456789abcdef'});assert(findings.some(x=>x.kind==='credential label'),'credential assignment was missed');assert(findings.every(x=>!Object.prototype.hasOwnProperty.call(x,'value')),'secret scanner exposed a matched value');
findings=core.scanSecretLikeText({ticket:'$krb5asrep$23$user@REALM:abcdef'});assert(findings.some(x=>x.kind==='Kerberos hash'),'Kerberos hash was missed');
const now=1_000_000,good=core.backupFreshness({at:now-10*60000},now,60*60000),soon=core.backupFreshness({at:now-50*60000},now,60*60000),expired=core.backupFreshness({at:now-70*60000},now,60*60000);assert(good.fresh&&!good.dueSoon&&!good.expired,'fresh backup state wrong');assert(soon.fresh&&soon.dueSoon&&!soon.expired,'due-soon backup state wrong');assert(!expired.fresh&&expired.expired,'expired backup state wrong');
const sum=core.preflightSummary([{state:'pass'},{state:'warn'},{state:'fail'}]);assert(sum.pass===1&&sum.warn===1&&sum.fail===1&&!sum.ok,'preflight summary failed');
console.log('reliability-safety tests passed');
