import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
let html=read('src/index.template.html');
html=html.replace(/\/\* @inject:style:([^*]+?) \*\//g,(_,f)=>read('src/styles/'+f.trim()));
html=html.replace(/\/\* @inject:script:([^*]+?) \*\//g,(_,f)=>read('src/js/'+f.trim()));
const manifest=JSON.parse(read('src/content/manifest.json'));
const reference=manifest.files.map(f=>read('src/content/'+f)).join('');
html=html.replace('<!-- @inject:reference -->',()=>reference);
if(/@inject:/.test(html)) throw new Error('Unresolved build injection marker');
fs.writeFileSync(path.join(root,'index.html'),html);
console.log('Built index.html ('+Buffer.byteLength(html).toLocaleString()+' bytes)');
