import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const fail=m=>{throw new Error(m)};
const html=read('index.html');
if(/@inject:/.test(html)) fail('Unresolved injection marker');
if(!/connect-src\s+'none'/.test(html)) fail("connect-src 'none' missing");
if(/<script\b[^>]*\bsrc\s*=/i.test(html)) fail('Runtime script source detected');
if(/<link\b[^>]*\brel=["']stylesheet["'][^>]*\bhref\s*=/i.test(html)) fail('Runtime stylesheet detected');
if(/<(?:script|img|link)\b[^>]*(?:src|href)=["']https?:\/\//i.test(html)) fail('Remote runtime resource detected');
const ids=[...html.matchAll(/\bid=["']([^"']+)["']/gi)].map(m=>m[1]),seen=new Set(),dupes=[];
for(const id of ids){if(seen.has(id))dupes.push(id);seen.add(id)}
if(dupes.length) fail('Duplicate IDs: '+[...new Set(dupes)].join(', '));
const hrefs=[...html.matchAll(/\bhref=["']#([^"']+)["']/gi)].map(m=>m[1]);
const missing=[...new Set(hrefs.filter(id=>!seen.has(id)))];
if(missing.length) fail('Broken anchors: '+missing.join(', '));
const jsFiles=fs.readdirSync(path.join(root,'src/js')).filter(x=>x.endsWith('.js')).sort();
const js=jsFiles.map(f=>read('src/js/'+f)).join('\n');
const inner=(js.match(/\.innerHTML\s*=/g)||[]).length;
if(inner>174) fail('innerHTML assignments increased: '+inner);
const util=read('src/js/00-core-utils.js');
if(!util.includes("'&#39;'")) fail('Single-quote escaping missing');
for(const f of jsFiles.filter(x=>x!=='00-core-utils.js')) if(/replace\(\/\[&<>/.test(read('src/js/'+f))) fail('Local HTML escaping remains in '+f);
const aliases=(js.match(/function\s+esc\(s\)\{return window\.OSCP_UTILS\.escapeHtml\(s\)\}/g)||[]).length;
if(aliases!==4) fail('Expected 4 esc aliases, got '+aliases);
const manifest=JSON.parse(read('src/content/manifest.json'));
const reference=manifest.files.map(f=>read('src/content/'+f)).join('');
if((reference.match(/<h2\s+id=/g)||[]).length!==39) fail('Reference section count changed');
if(!html.includes('V30 · EXAM ONLY · OFFLINE · NO AI')) fail('V30 badge missing');
if(!html.includes('window.OSCP_UTILS.examScore(ad,ss,70)')) fail('Score utility not wired');
if(!html.includes('window.OSCP_UTILS.evidenceMissing(t)')) fail('Evidence utility not wired');
console.log('Validation passed: '+ids.length+' IDs, 39 reference sections, '+inner+' innerHTML assignments');
